config/routes.rb
Buttafly::Engine.routes.draw do

  resources :artifacts, only: [:destroy] do
    member do
      patch 'revert'
    end
  end
  resources :legends

  resources :mappings do
    member do
      patch 'import'
      patch 'revert'
    end
  end
  resources :spreadsheets do
    resources :mappings
    resources :legends
    member do
      patch 'import'
      patch 'revert'
    end
  end

  root to: "spreadsheets#index"
end

app/models/buttafly/application_record.rb
module Buttafly
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/buttafly/artifact.rb
module Buttafly
  class Artifact < ApplicationRecord
    include Buttafly

    belongs_to :mapping, class_name: "Buttafly::Mapping"

    enum status: [ :was_new, :was_updated, :was_duplicate ]
    serialize :data

    def revert_record
      case status
      when "was_new"
        record_klass = data.keys.second.classify.constantize
        record_id = data["artifactable_id"]
        record = record_klass.find(record_id)
        artifact_attrs = data.values.second
        record_attrs = record.attributes.except("created_at", "updated_at", "id")
        if (record_attrs.merge artifact_attrs) == artifact_attrs
          record.delete
        end

      when "was_updated"
        record_klass = data.keys.second.classify.constantize
        record_id = data["artifactable_id"]
        record = record_klass.find(record_id)
        artifact_attrs = data.values.second
        record_attrs = record.attributes
        artifact_attrs.each do |key, value|
          record_attrs[key] = value
        end
        record.update(record_attrs)
      end
      self.delete
    end
  end
end

app/models/buttafly/legend.rb
module Buttafly
  class Legend < ApplicationRecord

    has_many :mappings,     dependent:    :destroy
    has_many :originables,  through:      :mappings,
                            source:       :originable,
                            source_type:  Buttafly.originable_model

    serialize :data
    serialize :originable_headers

    def default_name
      name.blank? ? targetable_model : name
    end
  end
end

app/models/buttafly/mapping.rb
module Buttafly
  class Mapping < ApplicationRecord

    require "tsortable"
    require "csv"
    require "json"
    require "roo"

    include AASM
    include Buttafly

    belongs_to :legend, class_name: "Buttafly::Legend"
    belongs_to :originable, polymorphic: true

    has_many :artifacts, foreign_key: :mapping_id, class_name: "Buttafly::Artifact"

    accepts_nested_attributes_for :legend
    accepts_nested_attributes_for :artifacts

    aasm do
      state :importable
      state :imported

      event :import do
        transitions from: :importable, to: :imported,
                                       after: :transmogrify
      end

      event :revert do
        transitions from: :imported, to: :importable,
                                       after: :revert_all_records
      end
    end

    def headers
      self.originable.originable_headers
    end

    def data
      legend.data
    end

    def targetable_models
      Buttafly::Targetable.models
    end

    def ancestors
      Targetable.ancestors_of(legend.targetable_model)
    end

    def get_parent(key, klass)
      if klass.nil?
        parent = key
      else
        parent = klassify(klass).reflect_on_association(key).class_name.downcase
      end
      parent
    end

    def create_records(row, klass = nil, hash=data)
      attrs = {}
      hash.each do |key, value|
        if value.is_a? Hash
          create_records(row, get_parent(key, klass), value)
        else
          attrs[key.to_s] = row[value]
        end
        unless klass.nil?
          parents = klassify(klass).reflect_on_all_associations(:belongs_to)
          parents.each do |parent|
            pc = klassify(parent.class_name)
            items = pc.where(hash[parent.class_name.to_s])
            unless items.empty?
              items.each do |item|
                parent_id = item.id
                attrs["#{parent.name.to_s}_id"] = parent_id
              end
            end
          end
        end
      end

      unless klass.nil?
        create_artifact(klass, attrs)
      end
    end

    def findable_attrs(model, all_attrs)
      attrs = []
      klass = model.to_s.classify.constantize
      klass.validators.select do |validator|
        if validator.is_a? ActiveRecord::Validations::UniquenessValidator
          validator.attributes.each do |attr|
            parents = klass.reflect_on_all_associations(:belongs_to).map(&:name)
            attrs << ((parents.include?(attr)) ? (attr.to_s + "_id") : attr.to_s)
          end
        end
      end
      (all_attrs.slice *attrs)
    end

    def create_artifact(model, attrs)
      attrs.stringify_keys!
      klass = klassify(model)
      case
      when record = klass.find_by(attrs)
        artifacts.create(status: "was_duplicate", data: {
                         "artifactable_id" => record.id, model => attrs} )
      when record = klass.find_by(findable_attrs(model, attrs))
        artifacts.create(status: "was_updated", data: {
                         "artifactable_id" => record.id, model => record.attributes} )
        record.update(attrs)
      when record = klass.create(attrs)
        arty = Buttafly::Artifact.create(mapping_id: self.id, status: "was_new", data: {
                         "artifactable_id" => record.id, model => attrs} )
      end
    end

    def transmogrify
      csv = CSV.open(originable.flat_file.path, headers:true).readlines
      csv.each { |row| create_records(row) }
    end

    def revert_all_records
      artifacts.each do |artifact|
        artifact.revert_record
      end
    end

  private

    def klassify(model)
      model.classify.constantize
    end
  end
end

app/models/buttafly/spreadsheet.rb
module Buttafly
  class Spreadsheet < ApplicationRecord

    include Originable

    mount_uploader :flat_file, Buttafly::FlatFileUploader

    validates :name,      uniqueness: true, allow_blank: true
  end
end

app/models/concerns/buttafly/originable.rb
module Buttafly
  module Originable

    extend ActiveSupport::Concern

    module ClassMethods

      def originable?
        true
      end
    end

    included do

      require "csv"
      require "json"
      require "roo"

      include AASM

      has_many :mappings, class_name: "Buttafly::Mapping", as: :originable, dependent: :destroy
      has_many :legends, class_name: "Buttafly::Legend", through: :mappings, as: :originable

      accepts_nested_attributes_for :legends

      aasm do
        state :uploaded, initial: true
        state :mapped
        state :imported
        state :archived

        event :map do
          transitions from: [:uploaded, :mapped, :imported], to: :mapped
        end

        event :import do
          transitions from: :mapped, to: :imported
        end

        event :archive do
          transitions from: [:uploaded, :mapped, :imported], to: :imported
        end
      end

      def originable_headers(file=flat_file.path)
        data = CSV.read(file)
        data.first
      end

      def legend_candidates
        Legend.where(originable_headers: originable_headers)
      end
    end
  end
end

app/controllers/buttafly/application_controller.rb
module Buttafly
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/buttafly/artifacts_controller.rb
require_dependency "buttafly/application_controller"

module Buttafly
  class ArtifactsController < ApplicationController
    before_action :set_artifact, only: [:revert, :destroy]

    def destroy

      if @artifact.destroy
        redirect_back fallback_location: root_path, notice: 'Artifact was destroyed.'
      end
    end

    def revert
      mapping = @artifact.mapping
      @artifact.revert_record
      redirect_back fallback_location: root_path, notice: 'Artifact was reverted.'
    end

    private

      def set_artifact
        @artifact = Artifact.find(params[:id])
      end

      def artifact_params
        params.require(:artifact).permit(:mapping_id)
      end
  end
end

app/controllers/buttafly/contents_controller.rb
require_dependency "buttafly/application_controller"

module Buttafly
  class ContentsController < ApplicationController
    before_action :set_content, only: [:show, :edit, :update, :destroy]
    before_action :set_originable_model, only: [:index]

    def index
      @contents = Buttafly::Spreadsheet.all
      # @contents = @originable_model.all
    end

    def show
    end

    def new
      @content = Content.new
    end

    def edit
    end

    def create
      @content = Content.new(content_params)

      if @content.save
        redirect_to @content, notice: 'Content was successfully created.'
      else
        render :new
      end
    end

    def update
      if @content.update(content_params)
        redirect_to @content, notice: 'Content was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @content.destroy
      redirect_to contents_url, notice: 'Content was successfully destroyed.'
    end

    private
      def set_content
        @content = Content.find(params[:id])
      end

      def set_originable_model
        # @originable_model = Buttafly.originable_model.classify.constantize
      end

      def content_params
        params.fetch(:content, {})
      end
  end
end

app/controllers/buttafly/legends_controller.rb
require_dependency "buttafly/application_controller"

module Buttafly

  class LegendsController < ApplicationController

    before_action :set_legend, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
      @targetable_model = @legend.targetable_model
      @originable_headers = @legend.originable_headers
    end

    def create
      @spreadsheet = Buttafly::Spreadsheet.find(params["spreadsheet_id"])
      @legend = @spreadsheet.legends.create(legend_params.merge(originable_headers: @spreadsheet.originable_headers))

      if @legend.save

        redirect_to edit_legend_path(@legend), notice: 'Legend was successfully created.'
      else
        render "spredsheets/show", @spreadsheet
      end
    end

    def update

      if @legend.update(legend_params)
        redirect_to edit_legend_url(@legend), notice: 'Legend was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @legend.destroy
      redirect_to root_url, notice: 'Legend was successfully destroyed.'
    end

    private
      def set_legend
        @legend = Legend.find(params[:id])
      end

      def legend_params
        params.require(:legend).permit!# (:originable_headers, :targetable_model, :data => {})
      end
  end
end

app/controllers/buttafly/mappings_controller.rb
require_dependency "buttafly/application_controller"

module Buttafly
  class MappingsController < ApplicationController
    before_action :set_mapping, only: [:show, :import, :revert, :destroy]

    def show
      @legend = @mapping.legend
      @originable = @mapping.originable
    end

    def create

      @spreadsheet = Buttafly::Spreadsheet.find(params[:spreadsheet_id])
      @mapping = @spreadsheet.mappings.new(legend_id: mapping_params[:legend_id] )
      if @mapping.save
        redirect_to @spreadsheet, notice: 'Mapping was successfully created.'
      else
        render :new
      end
    end

    def import
      if @mapping.import!
        redirect_to @mapping, notice: "Successfully imported rows."
      else
        redirect_to @mapping, alert: "Could not import rows."
      end
    end

    def revert
      if @mapping.revert!
        redirect_to @mapping, notice: "Successfully reverted."
      else
        redirect_to @mapping, alert: "Could not revert."
      end
    end

    def destroy
      @mapping.destroy
      redirect_to mappings_url, notice: 'Mapping was successfully destroyed.'
    end

    private
      def set_mapping
        @mapping = Mapping.find(params[:id])
      end

      def mapping_params
        params.require(:mapping).permit!
      end
  end
end

app/controllers/buttafly/spreadsheets_controller.rb
require_dependency "buttafly/application_controller"

module Buttafly
  class SpreadsheetsController < ApplicationController
    before_action :set_spreadsheet, only: [:show, :edit, :update, :destroy]
    before_action :set_originable_klass

    def index
      @spreadsheets = @originable_klass.all
    end

    def show
    end

    def new
      @spreadsheet = @originable_klass.new
    end

    def edit
    end

    def create
      @spreadsheet = @originable_klass.new(spreadsheet_params)
      if @spreadsheet.save
        redirect_to @spreadsheet, notice: 'Spreadsheet was successfully created.'
      else
        render :new
      end
    end

    def update
      if @spreadsheet.update(spreadsheet_params)
        redirect_to @spreadsheet, notice: 'Spreadsheet was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @spreadsheet.destroy
      redirect_to spreadsheets_url, notice: 'Spreadsheet was successfully destroyed.'
    end

    private

      def set_originable_klass
        @originable_klass = Buttafly.originable_model.classify.constantize
      end

      def set_spreadsheet
        set_originable_klass
        @spreadsheet = @originable_klass.find(params[:id])
      end

      def spreadsheet_params
        params.fetch(:spreadsheet, {}).permit(:name, :flat_file, :aasm_state, :uploader_id, :imported_at, :processed_at, :mtime)
      end
  end
end

app/helpers/buttafly/application_helper.rb
module Buttafly
  module ApplicationHelper
    def flash_class(level)
      case level
      when :notice
        "alert-info"
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-error"
      end
    end

    def main_app_name
      Rails.application.class.parent.name
    end

    def ancestors
      Buttafly::Targetable.ancestors_of(@targetable_model)
    end

    def children(parent, col, children=nil)
      children ||= {}
      @legend.data
      children[parent] = col
    end

    def event_buttons_for(model_with_aasm)
      buttons = []
      if model_with_aasm.respond_to? :aasm
        model_with_aasm.aasm.events.map(&:name).each do |a|
          action = a.to_s
          singularized_model = model_with_aasm.class.to_s.split(":").last.to_s.downcase
          path = eval("#{action}_#{singularized_model}_url(model_with_aasm)")
          id = "#{action}Mapping-#{model_with_aasm.id}"
          buttons << (button_to(path, method: :patch, class: btn_class(action), id: id) {action})
        end
      end
      buttons << (button_to(model_with_aasm, class: btn_class("destroy"), id: "destroy#{model_with_aasm.class}-#{model_with_aasm.id}") { "destroy" } )
    end

    def btn_class(action)
      hash = {
        "import" => "success",
        "revert" => "warning",
        "destroy" => "danger"
      }
      "btn-group btn btn-#{hash[action]}"
    end

    def mapping_selectors(model)
      Buttafly::Targetable.targetable_columns(model)
    end

    def legend_node(legend)
      legend_node = legend.data

    end

    def header_at(legend, lineage, column)
      "[\"#{lineage.join("\"][\"")}\"][\"#{column}\"]"
    end

    def locals(ancestor, f, i, parent=nil)
      lineage ||= []
      if parent.nil?
        lineage_parent = lineage
      else
        lineage_parent = lineage + parent
      end
      ancestors = ancestor.values.first.values.first
      lineage_parent << ancestor.keys.first.to_s
      locals = {
        f: f,
        i: i,
        lineage: lineage_parent,
        ancestors: ancestors,
        a: ancestor.keys.first,
        m: ancestor.values.first.first.first
      }
      locals
    end
  end
end

app/helpers/buttafly/artifacts_helper.rb
module Buttafly
  module ArtifactsHelper
  end
end

app/helpers/buttafly/contents_helper.rb
module Buttafly
  module ContentsHelper
  end
end

app/helpers/buttafly/legends_helper.rb
module Buttafly
  module LegendsHelper
  end
end

app/helpers/buttafly/mappings_helper.rb
module Buttafly
  module MappingsHelper
  end
end

app/helpers/buttafly/spreadsheets_helper.rb
module Buttafly
  module SpreadsheetsHelper
  end
end

app/views/buttafly/spreadsheets/_form.html.haml
= form_with(model: spreadsheet, local: true) do |form|
  - if spreadsheet.errors.any?
    #error_explanation
      %h2
        = pluralize(spreadsheet.errors.count, "error")
        prohibited this spreadsheet from being saved:
      %ul
        - spreadsheet.errors.full_messages.each do |message|
          %li= message

  .form-group
    = form.label :name
    = form.text_field :name, class: "form-control"
    %small#emailHelp.form-text.text-muted
  .form-group
    = form.file_field :flat_file, class: "form-control-file"
  = form.submit class: "btn btn-primary"

app/views/buttafly/spreadsheets/edit.html.haml
%h1 Editing Spreadsheet
= render 'form', spreadsheet: @spreadsheet
= link_to 'Show', @spreadsheet
|
= link_to 'Back', spreadsheets_path

app/views/buttafly/spreadsheets/index.html.haml
%table.table.table-hover
  %thead
    %tr
      %th{:scope => "col"} Name
      %th{:scope => "col"} Created at
      %th{:scope => "col"} Aasm state
      %th{:scope => "col"} Uploader
      %th{:scope => "col"} Imported at
      %th{:scope => "col"} Processed at
      %th{:scope => "col"}
      %th{:scope => "col"}
      %th{:scope => "col"}
  %tbody
    - @spreadsheets.each do |spreadsheet|
      %tr
        %td= spreadsheet.name.blank? ? spreadsheet.flat_file.to_s.split("/").last : spreadsheet.name
        %td= time_ago_in_words(spreadsheet.updated_at) + " ago"
        %td= spreadsheet.aasm_state
        %td= spreadsheet.uploader_id
        %td= spreadsheet.imported_at
        %td= spreadsheet.processed_at
        %td= link_to 'Show', spreadsheet
        %td= link_to 'Edit', edit_spreadsheet_path(spreadsheet)
        %td= button_to 'Destroy', spreadsheet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger"
%br/
= link_to 'New Spreadsheet', new_spreadsheet_path

app/views/buttafly/spreadsheets/new.html.haml
.card.card-body
  .col-sm-r
    %h3 New Spreadsheet
    %small.text-muted With faded secondary text
  .col-sm-8
    = render 'form', spreadsheet: @spreadsheet
    = link_to 'Back', spreadsheets_path

app/views/buttafly/spreadsheets/show.html.haml
.card.card-body
  %dl.row
    %dt.col-sm-3.text-right Host Application name
    %dd.col-sm-9= main_app_name
    %dt.col-sm-3.text-right Filename
    %dd.col-sm-9= @spreadsheet.name.blank? ? "no name supplied" : @spreadsheet.name

    %dt.col-sm-3.text-right Status
    %dd.col-sm-9= @spreadsheet.aasm_state
    %dt.col-sm-3.text-right Headers
    %dd.col-sm-9
      .text-info
        = @spreadsheet.originable_headers.join(" | ")
    %dt.col-sm-3.text-right
    %dd.col-sm-9

  .row
    .col
      .card.card-body
        = form_with url: spreadsheet_legends_path(@spreadsheet) do |f|
          = f.fields_for :legend do |f|
            .form-group
              = f.label "targetable model"
              = f.select("targetable_model", Buttafly::Targetable.models, {}, class: "form-control", id: "targetableModel")
            .form-group
              = f.submit "Create new legend", class: "btn btn-primary btn-block"
    .col
      .card.card-body
        = form_with url: spreadsheet_mappings_url(@spreadsheet) do |f|
          = f.fields_for :mapping do |f|
            .form-group
              = f.label "existing legends"
              = f.collection_select(:legend_id, @spreadsheet.legend_candidates, :id, :default_name, {}, class: "form-control", id: "existingLegend")
            .form-group
              = f.submit "Choose from existing legend", class: "btn btn-primary btn-block"
  %br
  .card.card-body
    .card-title Current mappings from this sheet to existing legends
    - @spreadsheet.mappings.each do |mapping|
      .row
        .col= link_to(mapping.legend.name, mapping.legend)
        .col= mapping.legend.targetable_model
        .col= mapping.aasm_state
        - event_buttons_for(mapping).each do |button|
          .col= button

    -# %table.table.table-hover
    -#   %thead
    -#     %tr
    -#       %th{:scope => "col"} Legend
    -#       %th{:scope => "col"} Targetable model
    -#       %th{:scope => "col"} Status
    -#       %th{:scope => "col"} Actions
    -#
    -#   %tbody
    -#     - @spreadsheet.mappings.each do |mapping|
    -#       %tr
    -#         %td= link_to(mapping.legend.name, mapping.legend)
    -#         %td= mapping.legend.targetable_model
    -#         %td= mapping.aasm_state
    -#         %td
    -#         %td.btn-group
    -#           - event_buttons_for(mapping).each do |button|
    -#             = button